blue/urls.py
from django.urls import path
from . import views

app_name = 'blue'

urlpatterns = [
    path('buat-reservasi-rs/', views.reservasirs, name='reservasirs'),
    path('list-reservasi-rs/', views.listreservasirs, name='listreservasirs'),
    path('ajax/load-semuaruangan/', views.load_semuaruangan, name='ajax_load_semuaruangan'),
    path('ajax/load-semuabed/', views.load_semuabed, name='ajax_load_semuabed'),
    path('delete-reservasi-rs/',views.delete_reservasi_rs, name='delete-reservasi-rs'),
    path('update-reservasi-rs/',views.update_reservasi_rs, name='update-reservasi-rs'),
    path('buat-faskes/',views.faskes, name='buat-faskes'),
    path('list-faskes/', views.listfaskes, name='listfaskes'),
    path('delete-faskes/',views.delete_faskes, name='delete-faskes'),
    path('update-faskes/',views.update_faskes, name='update-faskes'),
    path('detail-faskes/',views.detail_faskes, name='detail-faskes'),
    path('buat-jadwal/',views.jadwal, name='buat-jadwal'),
    path('list-jadwal/', views.listjadwal, name='listjadwal'),
    path('buat-rumah-sakit/',views.rumahsakit, name='buat-rumah-sakit'),
    path('list-rumah-sakit/', views.listrumahsakit, name='listrumahsakit'),
    path('update-rumah-sakit/',views.update_rumahsakit, name='update-rumah-sakit'),
    path('list-transaksi-rs/', views.listtransaksirs, name='listtransaksirs'),
    path('delete-transaksi-rs/',views.delete_transaksi_rs, name='delete-transaksi-rs'),
    path('update-transaksi-rs/',views.update_transaksi_rs, name='update-transaksi-rs'),
]

jingga/urls.py
from django.urls import path
from jingga.views import *

app_name = 'jingga'
urlpatterns = [
    path('', index, name="index"),
    path('listruanganhotel', listruanganhotel, name="listruanganhotel"),
    path('create-listruanganhotel', createlistruanganhotel, name="create-listruanganhotel"),
    path('ajax/load-kodehotel/', load_kodehotel, name='ajax-load-kodehotel'),
    path('update-ruanganhotel/', updateruanganhotel, name="update-ruanganhotel"),
    path('delete-ruanganhotel/', deleteruanganhotel, name="delete-ruanganhotel"),
    path('listreservasihotel/', listreservasihotel, name="listreservasihotel"),
    path('create-reservasihotel/', createreservasihotel, name="create-reservasihotel"),
    path('ajax/load-semuakodehotel/', load_semuakodehotel, name='ajax-load-semuakodehotel'),
    path('update-reservasihotel/', updatereservasihotel, name="update-reservasihotel"),
    path('delete-reservasihotel/', deletereservasihotel, name="delete-reservasihotel"),
    path('listtransaksihotel', listtransaksihotel, name="listtransaksihotel"),
    path('update-transaksihotel/', updatetransaksihotel, name="update-transaksihotel"),
    path('listtransaksibooking', listtransaksibooking, name="listtransaksibooking"),
]

tk4_b4/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('green.urls')),
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('jingga.urls')),
    path('', include('purple.urls')),
    path('', include('pasien.urls')),
    path('', include('blue.urls')),
    
]

jingga/models.py
from django.db import models

# Create your models here.

jingga/forms.py
from django import forms
from django.db import connection, transaction, IntegrityError, InternalError
from datetime import datetime
from django.core.exceptions import ValidationError

class CreateHotelRoomForm(forms.Form):
    cursor = connection.cursor()
    KODE_HOTEL = []
    JENIS_BED = [('King','King Bed'),('TwinSingle','Twin Single Bed')]
    TIPE_ROOM = [('Deluxe','Deluxe'),('Premium','Premium'),('Suite','Suite')]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute("SELECT kode, kode FROM SIRUCO.HOTEL")
            self.fields['kodehotel'].choices = cursor.fetchall()

    kodehotel = forms.ChoiceField(choices=KODE_HOTEL,
                                  widget=forms.Select(attrs={'class': 'form-control'}))

    koderoom = forms.CharField(widget = forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}))

    jenisbed = forms.ChoiceField(choices=JENIS_BED,
                                  widget=forms.Select(attrs={'class': 'form-control'}))
    tiperoom = forms.ChoiceField(choices=TIPE_ROOM,
                                  widget=forms.Select(attrs={'class': 'form-control'}))
    harga = forms.IntegerField(
                        widget=forms.NumberInput(attrs={'class': 'form-control'}))

    def save(self):
        cd = self.cleaned_data
        try:
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO SIRUCO.HOTEL_ROOM VALUES(%s, %s, %s, %s, %s)",
                               [cd.get("kodehotel"), cd.get('koderoom'), cd.get("jenisbed"),
                                cd.get("tiperoom"), cd.get("harga")])
        except IntegrityError:
            pass

    def clean(self):
        kodehotel = self.cleaned_data.get("kodehotel")
        koderoom = self.cleaned_data.get("koderoom")
        with connection.cursor() as cursor:
            cursor.execute("SELECT kodehotel, koderoom FROM SIRUCO.HOTEL_ROOM")
            existing_data = cursor.fetchall()
        if (kodehotel, koderoom) in existing_data:
            raise forms.ValidationError("Masukan data gagal")

class updatedataruangan(CreateHotelRoomForm):
    KODE_HOTEL = []
    JENIS_BED = [('King','King Bed'),('TwinSingle','Twin Single Bed')]
    TIPE_ROOM = [('Deluxe','Deluxe'),('Premium','Premium'),('Suite','Suite')]

    kodehotel = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}))

    koderoom = forms.CharField(widget = forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}))

    jenisbed = forms.ChoiceField(choices=JENIS_BED,widget=forms.Select(attrs={'class': 'form-control'}))

    tiperoom = forms.ChoiceField(choices=TIPE_ROOM,widget=forms.Select(attrs={'class': 'form-control'}))
    
    harga = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))

    def save_update(self):
        cd = self.cleaned_data
        try:
            with connection.cursor() as cursor:
                with transaction.atomic():
                    cursor.execute("""
                    UPDATE SIRUCO.HOTEL_ROOM SET jenisbed = %s, tipe = %s, harga = %s WHERE kodehotel=%s AND koderoom=%s""",
                            [cd.get("jenisbed"), cd.get("tiperoom"),
                            cd.get("harga"), cd.get("kodehotel"),
                            cd.get("koderoom")])
        except IntegrityError:
            pass

class CreateReservasiHotelForm(forms.Form):

    cursor = connection.cursor()
    
    
    cursor.execute("SELECT NIK FROM siruco.PASIEN")
    NIK_PASIEN = [(row[0],row[0]) for row in  cursor.fetchall()]
    nik = forms.ChoiceField(choices=NIK_PASIEN,
        widget=forms.Select(attrs={'class': 'form-control'}))

    tglmasuk = forms.DateField(
        widget=forms.SelectDateWidget,
        initial=datetime.now())

    tglkeluar = forms.DateField(
        widget=forms.SelectDateWidget,
        initial=datetime.now())

    cursor.execute("SELECT kode FROM SIRUCO.HOTEL")
    KODE_HOTEL = [(row[0],row[0]) for row in cursor.fetchall()]
    kodehotel = forms.ChoiceField(choices=KODE_HOTEL,
                                  widget=forms.Select(attrs={'class': 'form-control'}))
    
    kodehotelbersih = ""
    cursor.execute("SELECT koderoom FROM SIRUCO.HOTEL_ROOM WHERE kodehotel = %s", [kodehotelbersih])
    KODE_ROOM = [(row[0],row[0]) for row in cursor.fetchall()]
    koderoom = forms.ChoiceField(choices=KODE_ROOM,
                                  widget=forms.Select(attrs={'class': 'form-control'}),required=True)

    def save(self):
        cd = self.cleaned_data
        try:
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO SIRUCO.RESERVASI_HOTEL VALUES(%s, %s, %s, %s, %s)",
                               [cd.get("nik"), cd.get('tglmasuk'), cd.get('tglkeluar'),
                                cd.get("kodehotel"), cd.get("koderoom")])
        except IntegrityError:
            pass

    def clean(self):
        cd = self.cleaned_data
        kodepasien = cd.get("nik")
        tglmsk = cd.get("tglmasuk")
        tglklr = cd.get("tglkeluar")
        databersih = super().clean()

        if tglklr < tglmsk:
            raise forms.ValidationError("Tanggal keluar harus setelah tanggal masuk")
        with connection.cursor() as cursor:
            cursor.execute("SELECT kodepasien, tglmasuk FROM SIRUCO.RESERVASI_HOTEL")
            existing_data = cursor.fetchall()
        if (kodepasien, tglmsk) in existing_data:
            raise forms.ValidationError("Masukan data gagal")
        else: 
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO SIRUCO.RESERVASI_HOTEL VALUES(%s, %s, %s, %s, %s)",
                               [cd.get("nik"), cd.get('tglmasuk'), cd.get('tglkeluar'),
                                cd.get("kodehotel"), cd.get("koderoom")])

class UpdateDataReservasiHotel(forms.Form):
    kodepasien = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}))

    tglmasuk = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}))

    tglkeluar = forms.DateField(widget=forms.SelectDateWidget(attrs={'class': 'form-control'}))

    kodehotel = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}))
    
    koderoom = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}))

    def save_update(self):
        cd = self.cleaned_data
        try:
            with connection.cursor() as cursor:
                with transaction.atomic():
                    cursor.execute("""
                    UPDATE SIRUCO.RESERVASI_HOTEL SET tglkeluar = %s WHERE kodepasien=%s AND tglmasuk=%s""",
                            [cd.get("tglkeluar"),cd.get("kodepasien"),cd.get("tglmasuk")])
        except IntegrityError:
            pass

    def clean(self):
        cd = self.cleaned_data
        databersih = super().clean()
        tanggalmasuk = databersih['tglmasuk']
        tanggalkeluar = databersih['tglkeluar']
        if str(tanggalkeluar) < tanggalmasuk:
            raise forms.ValidationError("Tanggal keluar harus setelah tanggal masuk")
        kodepasien = cd.get("kodepasien")
        with connection.cursor() as cursor:
            cursor.execute("SELECT kodepasien, tglmasuk FROM SIRUCO.RESERVASI_HOTEL")
            existing_data = cursor.fetchall()
        if (kodepasien, tanggalmasuk) in existing_data:
            raise forms.ValidationError("Masukan data gagal")

class UpdateDataTransaksiHotel(forms.Form):
    cursor = connection.cursor()

    idtransaksi = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}))

    kodepasien = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}))

    tanggalpembayaran = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}),required=False)

    waktupembayaran = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}),required=False)
    
    totalbayar = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control','readonly':'readonly'}),required=False)

    statusbayar = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    def save_update(self):
        cd = self.cleaned_data
        try:
            with connection.cursor() as cursor:
                with transaction.atomic():
                    cursor.execute("""
                    UPDATE SIRUCO.TRANSAKSI_HOTEL SET statusbayar = %s WHERE idtransaksi = %s""",
                            [cd.get("statusbayar"),cd.get("idtransaksi")])
        except IntegrityError:
            pass

    def clean(self):
        cd = self.cleaned_data
        idtransaksi = cd.get("idtransaksi")
        with connection.cursor() as cursor:
            cursor.execute("SELECT idtransaksi FROM SIRUCO.TRANSAKSI_HOTEL")
            existing_data = cursor.fetchall()
        if (idtransaksi) in existing_data:
            raise forms.ValidationError("Masukan data gagal")
        if len(cd.get("statusbayar")) > 15:
            raise forms.ValidationError("Status Pembayaran Terlalu Panjang")

jingga/templates/CREATE-ListRuanganHotel.html
{% extends "base.html" %}
{% block content %}

    <div class="container-fluid">
        <div class='jumbotron justify-content-center' align="center">
            <h1>Create List Ruangan Hotel</h1>
            <hr>
            <h4>Pastikan Ruangan yang Anda Buat Sudah Sesuai</h4>
        </div>
        <div class="container d-flex justify-content-center" align="center">
            <form action="{% url 'jingga:create-listruanganhotel' %}" method="post" id="createruangan">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <h3><label for="{{ form.kodehotel.id_for_label }}">Kode Hotel</label></h3>
                {% if form.kodehotel.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.kodehotel.errors }}
                    </div>
                {% endif %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-bookmark"></i></span>
                    </div>
                    {{ form.kodehotel }}
                </div>

                <h3><label for="{{ form.koderoom.id_for_label }}">Kode Room</label></h3>
                {% if form.koderoom.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.koderoom.errors }}
                    </div>
                {% endif %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-bookmark"></i></span>
                    </div>
                    {{ form.koderoom }}
                </div>

                <h3><label for="{{ form.jenisbed.id_for_label }}">Jenis Bed</label></h3>
                {% if form.jenisbed.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.jenisbed.errors }}
                    </div>
                {% endif %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-bookmark"></i></span>
                    </div>
                    {{ form.jenisbed }}
                </div>

                <h3><label for="{{ form.tiperoom.id_for_label }}">Jenis Bed</label></h3>
                {% if form.tiperoom.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.tiperoom.errors }}
                    </div>
                {% endif %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-bookmark"></i></span>
                    </div>
                    {{ form.tiperoom }}
                </div>

                <h3><label for="{{ form.harga.id_for_label }}">Harga Room</label></h3>
                {% if form.harga.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ form.harga.errors }}
                    </div>
                {% endif %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-columns"></i></span>
                    </div>
                    {{ form.harga }}
                </div>
                <input class="btn btn-outline-primary" type="submit" value="Create">
            </form>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
            $("#id_kodehotel").change(function () {
            var url = "{% url 'jingga:ajax-load-kodehotel' %}";
            var kodehotel = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'kodehotel': kodehotel
                },
                success: function (data) {
                    $('#id_koderoom').val(data.insert_noRoom);
                }
            });
            });
        </script>



{% endblock %}

jingga/templates/CREATE-Reservasihotel.html
{% extends "base.html" %}
{% block content %}

    <div class="container-fluid">
        <div class='jumbotron justify-content-center' align="center">
            <h1>Create Reservasi Hotel</h1>
            <hr>
            <h4>Pastikan Reservasi Anda Sudah Sesuai</h4>
        </div>
        <div class="container d-flex justify-content-center" align="center">
            <form action="{% url 'jingga:create-reservasihotel' %}" method="post" id="reservasihotel">
                {% csrf_token %}
                {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                {{ form.non_field_errors }}
                </div>
                {% endif %}
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <div class="alert alert-danger alert-dismissable" role="alert">{{ message }}</div>
                    {% endfor %}
                </ul>
                {% endif %}
                
                <h4><label for="{{ form.nik.id_for_label }}">NIK</label></h4>
                {% if form.nik.errors %}
                <div class="alert alert-danger" role="alert">
                {{ form.nik.errors }}
                </div>
                {% endif %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-id-card-o"></i></span>
                    </div>
                    {{ form.nik }}
                </div>
    
                <h4><label for="{{ form.TanggalMasuk.id_for_label }}">Tanggal Masuk</label></h4>
                {% if form.tglmasuk.errors %}
                <div class="alert alert-danger" role="alert">
                {{ form.tglmasuk.errors }}
                </div>
                {% endif %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                    </div>
                    {{ form.tglmasuk }}
                </div>
    
    
                <h4><label for="{{ form.TanggalKeluar.id_for_label }}">Tanggal Keluar</label></h4>
                {% if form.tglkeluar.errors %}
                <div class="alert alert-danger" role="alert">
                {{ form.tglkeluar.errors }}
                </div>
                {% endif %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                    </div>
                    {{ form.tglkeluar }}
                </div>
    
                <h4><label for="{{ form.kodehotel.id_for_label }}">Kode Hotel</label></h4>
                {% if form.kodehotel.errors %}
                <div class="alert alert-danger" role="alert">
                {{ form.kodehotel.errors }}
                </div>
                {% endif %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-hospital-o"></i></span>
                    </div>
                    {{ form.kodehotel }}
                </div>
                
                <h4><label for="{{ form.koderoom.id_for_label }}">Kode Room</label></h4>
                {% if form.koderoom.errors %}
                <div class="alert alert-danger" role="alert">
                {{ form.koderoom.errors }}
                </div>
                {% endif %}
                <div class="input-group mb-3" id="result">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-hospital-o"></i></span>
                    </div>
                    {{ form.koderoom }}
                </div>

                <input class="btn btn-outline-success" type="submit" value="Register">
            </form>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
            $("#id_kodehotel").change(function () {
            var url = "{% url 'jingga:ajax-load-semuakodehotel' %}";
            var kodehotel = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'kodehotel': kodehotel
                },
                success: function (data) {
                    $('#id_koderoom').html(data);
                }
            });
            });
        </script>



{% endblock %}

jingga/templates/READ-Listreservasihotel.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Reservasi Hotel - SIRUCO
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>Reservasi Hotel</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>
    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-hover" align="center">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Kode Pasien</th>
                <th scope="col">Tanggal Masuk</th>
                <th scope="col">Tanggal Keluar</th>
                <th scope="col">Kode Hotel</th>
                <th scope="col">Kode Room</th>
                {% if request.session.role == 'ADMIN_SATGAS' %}
                    <th>Operasi</th>
                {% endif %}
            </tr>
            </thead>

            {% if request.session.role == 'ADMIN_SATGAS' %}
            {% for row in data %}
                <tr>
                    <td>{{ row.kodepasien }}</td>
                    <td>{{ row.tglmasuk }}</td>
                    <td>{{ row.tglkeluar }}</td>
                    <td>{{ row.kodehotel }}</td>
                    <td>{{ row.koderoom }}</td>
                    {% if request.session.role == 'ADMIN_SATGAS' %}
                    <td>
                        <form action="{% url 'jingga:update-reservasihotel' %}" method="get">
                            <input type="hidden" id="kodepasien" name="kodepasien" 
                                value="{{ row.kodepasien }}">
                            <input type="hidden" id="tglmasuk" name="tglmasuk" 
                                value="{{ row.tglmasuk }}">
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>

                        {% for kode in deletable %}
                        {% if row.kodepasien == kode.kodepasien and row.tglmasuk == kode.tglmasuk %}
                        <form action="{% url 'jingga:delete-reservasihotel' %}" method="get">
                            <input type="hidden" id="kodepasien" name="kodepasien" 
                                value="{{ row.kodepasien }}">
                            <input type="hidden" id="tglmasuk" name="tglmasuk" 
                                value="{{ row.tglmasuk }}">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                        {% endif %}
                        {% endfor %}
                        
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
            {% endif %}

            {% if request.session.role == "PENGGUNA_PUBLIK" %}
            {% for row in data %}
            {% if request.session.username == row.idpendaftar %}
                <tr>
                    <td>{{ row.kodepasien }}</td>
                    <td>{{ row.tglmasuk }}</td>
                    <td>{{ row.tglkeluar }}</td>
                    <td>{{ row.kodehotel }}</td>
                    <td>{{ row.koderoom }}</td>
                </tr>
            {% endif %}
            {% endfor %}
            {% endif %}
        </table>
    </div>
{% endblock %}
    

jingga/templates/READ-Listruanganhotel.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Ruangan Hotel - SIRUCO
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>Ruangan Hotel</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>
    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-hover" align="center">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Kode Hotel</th>
                <th scope="col">Kode Room</th>
                <th scope="col">Jenis Bed</th>
                <th scope="col">Tipe</th>
                <th scope="col">Harga</th>
                {% if request.session.role == 'ADMIN' %}
                    <th>Operasi</th>
                {% endif %}
            </tr>
            </thead>
            {% for row in data %}
                <tr>
                    <td>{{ row.kodehotel }}</td>
                    <td>{{ row.koderoom }}</td>
                    <td>{{ row.jenisbed }}</td>
                    <td>{{ row.tipe }}</td>
                    <td>{{ row.harga }}</td>
                    {% if request.session.role == 'ADMIN' %}
                    <td>
                        <form action="{% url 'jingga:update-ruanganhotel' %}" method="get">
                            <input type="hidden" id="kodehotel" name="kodehotel" value="{{ row.kodehotel }}">
                            <input type="hidden" id="koderoom" name="koderoom" value="{{ row.koderoom }}">
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>
                        
                        {% for kode in notreserved %}
                        {% if row.koderoom == kode.koderoom and row.kodehotel == kode.kodehotel %}
                        <form action="{% url 'jingga:delete-ruanganhotel' %}" method="get">
                            <input type="hidden" id="kodehotel" name="kodehotel"
                                   value="{{ row.kodehotel }}">
                            <input type="hidden" id="koderoom" name="koderoom"
                                   value="{{ row.koderoom }}">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                        {% endif %}
                        {% endfor %}

                        {% for kode in expire %}
                        {% if row.koderoom == kode.koderoom and row.kodehotel == kode.kodehotel%}
                        <form action="{% url 'jingga:delete-ruanganhotel' %}" method="get">
                            <input type="hidden" id="kodehotel" name="kodehotel"
                                   value="{{ row.kodehotel }}">
                            <input type="hidden" id="koderoom" name="koderoom"
                                   value="{{ row.koderoom }}">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                        {% endif %}
                        {% endfor %}

                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

jingga/templates/READ-Listtransaksibooking.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Transaksi Booking Hotel - SIRUCO
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>Transaksi Booking Hotel</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>
    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-hover" align="center">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Id Transaksi Booking</th>
                <th scope="col">Total Bayar</th>
                <th scope="col">Kode Pasien</th>
                <th scope="col">Tanggal Masuk</th>
            </tr>
            </thead>
            {% if request.session.role == "ADMIN_SATGAS" %}
            {% for row in data %}
                <tr>
                    <td>{{ row.idtransaksibooking }}</td>
                    <td>{{ row.totalbayar }}</td>
                    <td>{{ row.kodepasien }}</td>
                    <td>{{ row.tglmasuk }}</td>
                </tr>
            {% endfor %}
            {% endif %}
            
            {% if request.session.role == "PENGGUNA_PUBLIK" %}
            {% for row in data %}
            {% if request.session.username == row.idpendaftar %}
                <tr>
                    <td>{{ row.idtransaksibooking }}</td>
                    <td>{{ row.totalbayar }}</td>
                    <td>{{ row.kodepasien }}</td>
                    <td>{{ row.tglmasuk }}</td>
                </tr>
            {% endif %}
            {% endfor %}
            {% endif %}
        </table>
    </div>
{% endblock %}

jingga/templates/jingga.html
{% extends "base.html" %}
{% block content %}

<h1>awokwowkwowkw</h1>



{% endblock %}