blue/urls.py
from django.urls import path
from . import views

app_name = 'blue'

urlpatterns = [
    path('buat-reservasi-rs/', views.reservasirs, name='reservasirs'),
    path('list-reservasi-rs/', views.listreservasirs, name='listreservasirs'),
    path('ajax/load-semuaruangan/', views.load_semuaruangan, name='ajax_load_semuaruangan'),
    path('ajax/load-semuabed/', views.load_semuabed, name='ajax_load_semuabed'),
    path('delete-reservasi-rs/',views.delete_reservasi_rs, name='delete-reservasi-rs'),
    path('update-reservasi-rs/',views.update_reservasi_rs, name='update-reservasi-rs'),
    path('buat-faskes/',views.faskes, name='buat-faskes'),
    path('list-faskes/', views.listfaskes, name='listfaskes'),
    path('delete-faskes/',views.delete_faskes, name='delete-faskes'),
    path('update-faskes/',views.update_faskes, name='update-faskes'),
    path('detail-faskes/',views.detail_faskes, name='detail-faskes'),
    path('buat-jadwal/',views.jadwal, name='buat-jadwal'),
    path('list-jadwal/', views.listjadwal, name='listjadwal'),
    path('buat-rumah-sakit/',views.rumahsakit, name='buat-rumah-sakit'),
    path('list-rumah-sakit/', views.listrumahsakit, name='listrumahsakit'),
    path('update-rumah-sakit/',views.update_rumahsakit, name='update-rumah-sakit'),
    path('list-transaksi-rs/', views.listtransaksirs, name='listtransaksirs'),
    path('delete-transaksi-rs/',views.delete_transaksi_rs, name='delete-transaksi-rs'),
    path('update-transaksi-rs/',views.update_transaksi_rs, name='update-transaksi-rs'),
]

tk4_b4/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('green.urls')),
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('jingga.urls')),
    path('', include('purple.urls')),
    path('', include('pasien.urls')),
    path('', include('blue.urls')),
    
]

blue/models.py
from django.db import models

# Create your models here.

blue/forms.py
from django import forms
from django.db import connection
from datetime import datetime
from django.core.exceptions import ValidationError

class CreateReservasi (forms.Form):
    cursor = connection.cursor()
    #NIK
    NIK = forms.ChoiceField(choices=[],
        widget=forms.Select(attrs={'class': 'form-control'}))

    #TanggalMasuk            
    TanggalMasuk = forms.DateField(
        initial=datetime.now())

    #Tanggal Keluar
    TanggalKeluar = forms.DateField(
        initial=datetime.now())

    def clean_TanggalKeluar (self):
        cleaned_data = super().clean()
        DateOut = cleaned_data['TanggalKeluar']
        DateIn = cleaned_data['TanggalMasuk']
        if DateIn > DateOut or DateIn == DateOut:
            raise forms.ValidationError("Tanggal masuk harus sebelum tanggal keluar")
        return DateOut

    #kode RS
    KodeRS = forms.ChoiceField(choices=[],
        widget=forms.Select(attrs={'class': 'form-control'}))
    def __init__(self, *args, **kwargs):
        super(CreateReservasi, self).__init__(*args, **kwargs)
        cursor = connection.cursor()
        cursor.execute("SELECT Kode_Faskes FROM siruco.RUMAH_SAKIT")
        PilihanKodeRS = [('------','------')]+[(row[0],row[0]) for row in  cursor.fetchall()]
        self.fields['KodeRS'].choices = PilihanKodeRS
        cursor.execute("SELECT NIK FROM siruco.PASIEN")
        PilihanNikPasien = [(row[0],row[0]) for row in  cursor.fetchall()]
        self.fields['NIK'].choices = PilihanNikPasien
    
    #Kode Ruangan
    kodeRSbersih = ""
    def clean_kodeRS (self):
        KodeRSbersih = self.cleaned_data.get("kodeRS")
    cursor.execute("SELECT KodeRuangan FROM siruco.Ruangan_RS WHERE kodeRS =%s",[kodeRSbersih])
    PilihanKodeRuangan = [(row[0],row[0]) for row in  cursor.fetchall()]
    KodeRuangan = forms.ChoiceField(choices=PilihanKodeRuangan, widget=forms.Select(attrs={'class': 'form-control'}))
    
    #KodeBed
    kodeRuanganBersih= ""
    def clean_kodeRuangan (self):
        KodeRuanganBersih = self.cleaned_data.get("kodeRuangan")
    cursor.execute("SELECT KodeBed FROM siruco.BED_RS WHERE kodeRuangan =%s",[kodeRuanganBersih])
    PilihanKodeBed = [(row[0],row[0]) for row in  cursor.fetchall()]
    KodeBed = forms.ChoiceField(choices=PilihanKodeBed,
    widget=forms.Select(attrs={'class': 'form-control'}))

    def save(self):
        NIK = self.cleaned_data.get('NIK')
        TanggalMasuk = self.cleaned_data.get('TanggalMasuk')
        TanggalKeluar = self.cleaned_data.get('TanggalKeluar')
        KodeRS = self.cleaned_data.get('KodeRS')
        KodeRuangan = self.cleaned_data.get('KodeRuangan')
        KodeBed = self.cleaned_data.get('KodeBed')
        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO SIRUCO")
            cursor.execute("INSERT INTO siruco.RESERVASI_RS VALUES(%s,%s,%s,%s,%s,%s)",
                           [NIK, TanggalMasuk, TanggalKeluar,KodeRS,KodeRuangan,KodeBed])

class UpdateReservasi (forms.Form):
    cursor = connection.cursor()
    #NIK
    kodepasien = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))

    #TanggalMasuk            
    tglmasuk = forms.DateField(widget=forms.DateInput(attrs={'readonly':'readonly'}))

    #Tanggal Keluar
    tglkeluar = forms.DateField(
        initial=datetime.now())

    def clean_tglkeluar (self):
        cleaned_data = super().clean()
        DateOut = cleaned_data['tglkeluar']
        DateIn = cleaned_data['tglmasuk']
        if DateIn > DateOut or DateIn == DateOut :
            raise forms.ValidationError("Tanggal masuk harus sebelum tanggal keluar")
        return DateOut

    #kode RS
    koders = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    
    #Kode Ruangan
    koderuangan = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))

    #KodeBed
    kodebed = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))

    def save(self):
        kodepasien = self.cleaned_data.get('kodepasien')
        tglmasuk = self.cleaned_data.get('tglmasuk')
        tglkeluar = self.cleaned_data.get('tglkeluar')
        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO SIRUCO")
            cursor.execute("UPDATE SIRUCO.Ruangan_rs SET jmlbed = 10")
            cursor.execute("UPDATE SIRUCO.RESERVASI_RS SET tglkeluar = %s where kodepasien = %s and tglmasuk = %s ",
                           [tglkeluar,kodepasien, tglmasuk])
        
class CreateFaskes (forms.Form):
    Kode = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Tipe = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),max_length=30)
    Nama = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=50)
    StatusMilik = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),max_length=30)
    Jalan = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30)
    Kelurahan = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30)
    Kecamatan = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30)
    Kabkot = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30)
    Prov = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30)

    def save(self):
        Kode = self.cleaned_data.get('Kode')
        Tipe = self.cleaned_data.get('Tipe')
        Nama = self.cleaned_data.get('Nama')
        StatusMilik = self.cleaned_data.get('StatusMilik')
        Jalan = self.cleaned_data.get('Jalan')
        Kelurahan = self.cleaned_data.get('Kelurahan')
        Kecamatan = self.cleaned_data.get('Kecamatan')
        Kabkot = self.cleaned_data.get('Kabkot')
        Prov = self.cleaned_data.get('Prov')
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO SIRUCO.FASKES VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s)",
                           [Kode,Tipe,Nama,StatusMilik,Jalan,Kelurahan,Kecamatan,Kabkot,Prov])

class UpdateFaskes (forms.Form):
    cursor = connection.cursor()

    kode = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    tipe = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),max_length=30)
    nama = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=50)
    statusmilik = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),max_length=30)
    jalan = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30)
    kelurahan = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30)
    kecamatan = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30)
    kabkot = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30)
    prov = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=30)

    def save(self):
        kode = self.cleaned_data.get('kode')
        tipe = self.cleaned_data.get('tipe')
        nama = self.cleaned_data.get('nama')
        statusmilik = self.cleaned_data.get('statusmilik')
        jalan = self.cleaned_data.get('jalan')
        kelurahan = self.cleaned_data.get('kelurahan')
        kecamatan = self.cleaned_data.get('kecamatan')
        kabkot = self.cleaned_data.get('kabkot')
        prov = self.cleaned_data.get('prov')
        with connection.cursor() as cursor:
            cursor.execute("UPDATE SIRUCO.FASKES SET Tipe = %s,Nama = %s,StatusMilik = %s,Jalan = %s,Kelurahan = %s,Kecamatan = %s,Kabkot = %s,Prov = %s WHERE Kode = %s ",
                           [tipe,nama,statusmilik,jalan,kelurahan,kecamatan,kabkot,prov,kode])

##################################

class CreateJadwalFaskes (forms.Form):
    
    #Kode Faskes
    kode_faskes = forms.ChoiceField(choices =[], widget=forms.Select(attrs={'class': 'form-control'}))
    def __init__(self, *args, **kwargs):
        cursor = connection.cursor()
        super(CreateJadwalFaskes, self).__init__(*args, **kwargs)
        cursor.execute("SELECT kode FROM siruco.faskes ORDER BY kode")
        PilihanFaskes = [(row[0],row[0]) for row in  cursor.fetchall()]
        self.fields['kode_faskes'].choices = PilihanFaskes
    shift = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),max_length=15)
    tanggal = forms.DateField(initial=datetime.now())


    def save(self):
        kode_faskes = self.cleaned_data.get('kode_faskes')
        shift = self.cleaned_data.get('shift')
        tanggal = self.cleaned_data.get('tanggal')
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO SIRUCO.JADWAL VALUES(%s,%s,%s)",
                           [kode_faskes,shift,tanggal])

###############################################

class CreateRumahSakit (forms.Form):
    cursor = connection.cursor()
    
    #Kode Faskes
    kode_faskes = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}))
    isrujukan = forms.BooleanField(required=False)


    def save(self):
        kode_faskes = self.cleaned_data.get('kode_faskes')
        isrujukan = self.cleaned_data.get('isrujukan')
        rujukan = 0
        if(isrujukan == True):
            rujukan=1
        print(rujukan)
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO SIRUCO.RUMAH_SAKIT VALUES(%s,%s)",[kode_faskes,rujukan])

class UpdateRumahSakit (forms.Form):
    cursor = connection.cursor()

    kode_faskes = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    isrujukan = forms.BooleanField(required=False)


    def save(self):
        kode_faskes = self.cleaned_data.get('kode_faskes')
        isrujukan = self.cleaned_data.get('isrujukan')
        rujukan = 0
        if(isrujukan == True):
            rujukan=1

blue/templates/ListFaskes.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    List Fasilitas Kesehatan
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>List Fasilitas Kesehatan</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>
    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-hover" align="center">
            <thead class="thead-dark">
            <tr>
                <th>No.</th>
                <th>Kode Faskes</th>
                <th>Tipe</th>
                <th>Nama Faskes</th>
                {% if request.session.role == 'ADMIN_SATGAS' %}
                    <th>Operasi</th>
                {% endif %}
            </tr>
            </thead>
            {% for row in data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.kode }}</td>
                    <td>{{ row.tipe }}</td>
                    <td>{{ row.nama }}</td>
                    {% if request.session.role == 'ADMIN_SATGAS' %}
                    <td>
                        <form action="{% url 'blue:delete-faskes' %}" method="get">
                            <input type="hidden" id="faskes" name="faskes" value="{{ row.kode }}">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>

                        <form action="{% url 'blue:update-faskes' %}" method="get">
                            <input type="hidden" id="faskes" name="faskes" value="{{ row.kode}}">
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>

                        <form action="{% url 'blue:detail-faskes' %}" method="get">
                            <input type="hidden" id="faskes" name="faskes" value="{{ row.kode}}">
                            <input type="submit" class="btn btn-success" value="Detail">
                        </form>
        
                    </td>
                    {% endif %}
                </tr>
                
            {% endfor %}

        </table>
        
    </div>


{% endblock %}

blue/templates/ListReservasiRS.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    List RESERVSI RS
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>List Reservasi RS</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>
    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-hover" align="center">
            <thead class="thead-dark">
            <tr>
                <th>No.</th>
                <th>Kode Pasien</th>
                <th>Tanggal Masuk</th>
                <th>Tanggal Keluar</th>
                <th>Kode RS</th>
                <th>Kode Ruangan</th>
                <th>Kode Bed</th>
                {% if request.session.role == 'ADMIN_SATGAS' %}
                    <th>Operasi</th>
                {% endif %}
            </tr>
            </thead>
            {% for row in data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.kodepasien }}</td>
                    <td>{{ row.tglmasuk }}</td>
                    <td>{{ row.tglkeluar }}</td>
                    <td>{{ row.koders }}</td>
                    <td>{{ row.koderuangan }}</td>
                    <td>{{ row.kodebed}}</td>
                    {% if request.session.role == 'ADMIN_SATGAS' %}
                    <td>
                        {% if row.tglmasuk > today %}
                        <form action="{% url 'blue:delete-reservasi-rs' %}" method="get">
                            <input type="hidden" id="pasien" name="pasien" value="{{ row.kodepasien }}">
                            <input type="hidden" id="tgl" name="tgl" value="{{ row.tglmasuk }}">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                        {% endif %}

                        <form action="{% url 'blue:update-reservasi-rs' %}" method="get">
                            <input type="hidden" id="pasien" name="pasien" value="{{ row.kodepasien }}">
                            <input type="hidden" id="tgl" name="tgl" value="{{ row.tglmasuk }}">
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>
        
                    </td>
                    {% endif %}
                </tr>
                
            {% endfor %}

        </table>
        
    </div>
    {% if request.session.role == 'ADMIN_SATGAS' %}
    <div class="container d-flex justify-content-center" align="center" style="margin-bottom: 1rem">
        <form action="{% url 'blue:reservasirs' %}" method="get">
            <input type="submit" class="btn btn-danger" value="Buat Reservasi">
        </form>
    </div>
    {% endif %}

{% endblock %}

blue/templates/ListRumahSakit.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Daftar Rumah Sakit
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>List Rumah Sakit</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>
    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-hover" align="center">
            <thead class="thead-dark">
            <tr>
                <th>No.</th>
                <th>Kode Faskes</th>
                <th>IsRujukan</th>
                <th>Operasi</th>
            </tr>
            </thead>
            {% for row in data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.kode_faskes }}</td>
                    {% if row.isrujukan == '1' %}
                    <td><i class="fa fa-check-square"></i></td>
                    {% endif %}
                    {% if row.isrujukan == '0' %}
                    <td><i class="fa fa-square-o"></i></td>
                    {% endif %}
                    <td>
                        <form action="{% url 'blue:update-rumah-sakit' %}" method="get">
                            <input type="hidden" id="faskes" name="faskes" value="{{ row.kode_faskes}}">
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>
                    </td>
                </tr>
                
            {% endfor %}

        </table>
        
    </div>


{% endblock %}

blue/templates/reservasi_rumah_sakit.html
{% extends "base.html" %}
{% load static %}

{% block title %}SIRUCO - Reservasi Rumah sakit{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>Buat Reservasi Rumah Sakit</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'blue:reservasirs' %}" method="post" id="reservasi" data-semuaruangan-url="{% url 'blue:ajax_load_semuaruangan' %}" data-semuabed-url="{% url 'blue:ajax_load_semuabed' %}">
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
            </div>
            {% endif %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-danger alert-dismissable" role="alert">{{ message }}</div>
                {% endfor %}
            </ul>
            {% endif %}
            
            <h4><label for="{{ form.nik.id_for_label }}">NIK</label></h4>
            {% if form.nik.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.nik.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-id-card-o"></i></span>
                </div>
                {{ form.NIK }}
            </div>

            <h4><label for="{{ form.TanggalMasuk.id_for_label }}">Tanggal Masuk</label></h4>
            {% if form.TanggalMasuk.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.TanggalMasuk.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                </div>
                {{ form.TanggalMasuk }}
            </div>


            <h4><label for="{{ form.TanggalKeluar.id_for_label }}">Tanggal Keluar</label></h4>
            {% if form.TanggalKeluar.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.TanggalKeluar.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                </div>
                {{ form.TanggalKeluar }}
            </div>

            <h4><label for="{{ form.KodeRS.id_for_label }}">Kode RS</label></h4>
            {% if form.KodeRS.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodeRS.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-hospital-o"></i></span>
                </div>
                {{ form.KodeRS }}
            </div>
            
            <h4><label for="{{ form.KodeRuangan.id_for_label }}">Kode Ruangan</label></h4>
            {% if form.KodeRuangan.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodeRuangan.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-hospital-o"></i></span>
                </div>
                {{ form.KodeRuangan }}
            </div>

            <h4><label for="{{ form.KodeBed.id_for_label }}">Kode Bed</label></h4>
            {% if form.KodeBed.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodeBed.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-hospital-o"></i></span>
                </div>
                {{ form.KodeBed }}
            </div>
            <input class="btn btn-outline-success" style="margin-bottom: 1rem;" type="submit" value="Buat">
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_KodeRS.form-control").change(function () {
        var url = $("#reservasi").attr("data-semuaruangan-url"); 
        var KodeRS = $(this).val(); 

        $.ajax({                      
            url: url,                   
            data: {
            'KodeRS': KodeRS    
            },
            success: function (data) {  
            $("#id_KodeRuangan.form-control").html(data); 
            }
        });

        });

        $("#id_KodeRuangan.form-control").change(function () {
        var url = $("#reservasi").attr("data-semuabed-url"); 
        var KodeRuangan = $(this).val();

        $.ajax({                   
            url: url,               
            data: {
            'KodeRuangan': KodeRuangan    
            },
            success: function (data) {  
            $("#id_KodeBed.form-control").html(data);
            }
        });

        });
    </script>



{% endblock %}

blue/templates/update_reservasi_rs.html
{% extends "base.html" %}
{% load static %}

{% block title %}SIRUCO - Update Rumah sakit{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>Update Reservasi Rumah Sakit</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'blue:update-reservasi-rs' %}" method="post" id="reservasi" data-semuaruangan-url="{% url 'blue:ajax_load_semuaruangan' %}" data-semuabed-url="{% url 'blue:ajax_load_semuabed' %}">
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
            </div>
            {% endif %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-danger alert-dismissable" role="alert">{{ message }}</div>
                {% endfor %}
            </ul>
            {% endif %}
            
            <h4><label for="{{ form.kodepasien.id_for_label }}">NIK</label></h4>
            {% if form.kodepasien.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.kodepasien.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-id-card-o"></i></span>
                </div>
                {{ form.kodepasien }}
            </div>

            <h4><label for="{{ form.tglmasuk.id_for_label }}">Tanggal Masuk</label></h4>
            {% if form.tglmasuk.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.tglmasuk.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3" >
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                </div>
                {{ form.tglmasuk }}
            </div>


            <h4><label for="{{ form.tglkeluar.id_for_label }}">Tanggal Keluar</label></h4>
            {% if form.tglkeluar.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.tglkeluar.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                </div>
                {{ form.tglkeluar }}
            </div>

            <h4><label for="{{ form.koders.id_for_label }}">Kode RS</label></h4>
            {% if form.koders.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.koders.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-hospital-o"></i></span>
                </div>
                {{ form.koders }}
            </div>
            
            <h4><label for="{{ form.koderuangan.id_for_label }}">Kode Ruangan</label></h4>
            {% if form.koderuangan.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.koderuangan.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-hospital-o"></i></span>
                </div>
                {{ form.koderuangan }}
            </div>

            <h4><label for="{{ form.kodebed.id_for_label }}">Kode Bed</label></h4>
            {% if form.kodebed.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.kodebed.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-hospital-o"></i></span>
                </div>
                {{ form.kodebed }}
            </div>
            <input class="btn btn-outline-success" type="submit" value="Update">
        </form>
    </div>


{% endblock %}