blue/urls.py
from django.urls import path
from . import views

app_name = 'blue'

urlpatterns = [
    path('buat-reservasi-rs/', views.reservasirs, name='reservasirs'),
    path('list-reservasi-rs/', views.listreservasirs, name='listreservasirs'),
    path('ajax/load-semuaruangan/', views.load_semuaruangan, name='ajax_load_semuaruangan'),
    path('ajax/load-semuabed/', views.load_semuabed, name='ajax_load_semuabed'),
    path('delete-reservasi-rs/',views.delete_reservasi_rs, name='delete-reservasi-rs'),
    path('update-reservasi-rs/',views.update_reservasi_rs, name='update-reservasi-rs'),
    path('buat-faskes/',views.faskes, name='buat-faskes'),
    path('list-faskes/', views.listfaskes, name='listfaskes'),
    path('delete-faskes/',views.delete_faskes, name='delete-faskes'),
    path('update-faskes/',views.update_faskes, name='update-faskes'),
    path('detail-faskes/',views.detail_faskes, name='detail-faskes'),
    path('buat-jadwal/',views.jadwal, name='buat-jadwal'),
    path('list-jadwal/', views.listjadwal, name='listjadwal'),
    path('buat-rumah-sakit/',views.rumahsakit, name='buat-rumah-sakit'),
    path('list-rumah-sakit/', views.listrumahsakit, name='listrumahsakit'),
    path('update-rumah-sakit/',views.update_rumahsakit, name='update-rumah-sakit'),
    path('list-transaksi-rs/', views.listtransaksirs, name='listtransaksirs'),
    path('delete-transaksi-rs/',views.delete_transaksi_rs, name='delete-transaksi-rs'),
    path('update-transaksi-rs/',views.update_transaksi_rs, name='update-transaksi-rs'),
]

green/urls.py
from django.urls import path
from . import views

app_name = 'green'

urlpatterns = [
    path('create_transaksi_makan/', views.create_transaksi_makan, name='create_transaksi_makan'),
    path('list_transaksi_makan/', views.list_transaksi_makan, name='list_transaksi_makan'),
    path('update_transaksi_makan/', views.update_transaksi_makan, name='update_transaksi_makan'),
    path('delete_transaksi_makan/', views.delete_transaksi_makan, name='delete_transaksi_makan'),
    path('detail_transaksi_makan/', views.detail_transaksi_makan, name='detail_transaksi_makan'),

    path('create_paket_makan/', views.create_paket_makan, name='create_paket_makan'),
    path('list_paket_makan/', views.list_paket_makan, name='list_paket_makan'),
    path('update_paket_makan/', views.update_paket_makan, name='update_paket_makan'),
    path('delete_paket_makan/', views.delete_paket_makan, name='delete_paket_makan'),

    # path('create_hotel/', views.create_hotel, name='create_hotel'),
    path('list_hotel/', views.list_hotel, name='list_hotel'),
    path('update_hotel/', views.update_hotel, name='update_hotel'),
]

tk4_b4/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('green.urls')),
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('jingga.urls')),
    path('', include('purple.urls')),
    path('', include('pasien.urls')),
    path('', include('blue.urls')),
    
]

green/models.py
from django.db import models

# Create your models here.

green/forms.py
from django import forms
from django.db import connection
from datetime import datetime
from django.core.exceptions import ValidationError

class CreateTransaksiMakan(forms.Form):
    cursor = connection.cursor()

class UpdateTransaksiMakan(forms.Form):
    cursor = connection.cursor()

class CreatePaketMakan(forms.Form):
    cursor = connection.cursor()

class UpdatePaketMakan(forms.Form):
    cursor = connection.cursor()

class UpdateHotel(forms.Form):
    cursor = connection.cursor()

green/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db import connection, transaction, IntegrityError
from green.forms import *
from django.core import serializers
from django.http import JsonResponse, HttpResponseRedirect
from homepage.views import user_login_required
from django.urls import reverse

# Create your views here.
def user_login_required(function):
    def wrapper(request, *args, **kwargs):
        email = request.session.get('username')
        if email is None:
            return redirect('/login/')
        else:
            return function(request, *args, **kwargs)
    return wrapper


def cursor_fetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]


@user_login_required
def create_transaksi_makan(request):
    if request.session.get("role") != 'ADMIN_SATGAS' or request.session.get("role") == 'PENGGUNA_PUBLIK':
        return redirect('/')
    if request.method == 'POST':
        form = CreateTransaksiMakan(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/list_transaksi_makan/")
    if request.method == 'GET':
        form = CreateTransaksiMakan()
    context = {'form': form}
    return render(request, "CreateTransaksiMakan.html", context)


@user_login_required
def list_transaksi_makan(request):
    if request.session.get("role") == 'ADMIN_SATGAS' or request.session.get("role") == 'PENGGUNA_PUBLIK':
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM SIRUCO.TRANSAKSI_MAKAN")
            hasil = cursor_fetchall(cursor)
        context = {'data' : hasil}
    else:
        return redirect('/')
    return render(request, "ListTransaksiMakan.html", context)


@user_login_required
def detail_transaksi_makan(request):
    if request.session.get("role") == "ADMIN_SATGAS":
        idtransaksimakan = request.GET.get('idtransaksimakan')
        if idtransaksimakan is None:
            return redirect('/list_transaksi_makan/')
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM TRANSAKSI_MAKAN")

            cursor.execute("SELECT * FROM PAKET_MAKAN WHERE kodepaket=%s", [idtransaksimakan])

            cursor.execute("SELECT PM.kodepaket, PM.harga, TM.totalbayar FROM PAKET_MAKAN PM JOIN DAFTAR_PESAN DP ON DP.kodepaket = PM.kodepaket JOIN TRANSAKSI_MAKAN TM ON TM.idtransaksimakan = DP.idtransaksimakan GROUP BY PM.kodepaket, PM.harga, TM.totalbayar", [idtransaksimakan])
            
            # q1 = cursor.execute("SELECT * FROM SIRUCO.TRANSAKSI_MAKAN")
            # q2 = cursor.execute("SELECT PM.kodepaket, PM.harga, TM.totalbayar FROM SIRUCO.PAKET_MAKAN PM JOIN DAFTAR_PESAN DP ON DP.kodepaket = PM.kodepaket JOIN TRANSAKSI_MAKAN TM ON TM.idtransaksimakan = DP.idtransaksimakan GROUP BY PM.kodepaket, PM.harga, TM.totalbayar", [transaksi_makan])
            # queries = [q1, q2]
            # results = cursor.execute(";".join(queries), multi=True)
            hasil = cursor_fetchall(cursor)
        context = {'data' : hasil}
    else:
        return redirect('/')
    return render(request, "DetailTransaksiMakan.html", context)


@user_login_required
def update_transaksi_makan(request):
    if request.session.get("role") != "ADMIN_SATGAS":
        return redirect('/')
    if request.method == 'POST':
        form = UpdateTransaksiMakan(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/list_transaksi_makan/')
    elif request.method == 'GET':
        idtransaksimakan = request.GET.get('idtransaksimakan')
        if idtransaksimakan is None:
            return redirect('/list_transaksi_makan/')
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM SIRUCO.TRANSAKSI_MAKAN WHERE NOT EXISTS (SELECT statusbayar FROM SIRUCO.TRANSAKSI_HOTEL WHERE statusbayar='Lunas')", [idtransaksimakan])
            hasil = cursor_fetchall(cursor)
        context = {'form': form}
        return render(request, "UpdateTransaksiMakan.html", context)
    

@user_login_required
def delete_transaksi_makan(request):
    if request.method == "GET":
        idtransaksimakan = request.GET.get('idtransaksimakan')
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM SIRUCO.TRANSAKSI_MAKAN WHERE idtransaksimakan=%s", [idtransaksimakan])
    return redirect('/list_transaksi_makan')


@user_login_required
def create_paket_makan(request):
    if request.session.get("role") != 'ADMIN':
        return redirect('/')
    if request.method == 'POST':
        form = CreateTransaksiMakan(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/list_paket_makan/")
    if request.method == 'GET':
        form = CreatePaketMakan()
    context = {'form': form}
    return render(request, "CreatePaketMakan.html", context)


@user_login_required
def list_paket_makan(request):
    if request.session.get("role") == 'ADMIN_SATGAS' or request.session.get("role") == 'PENGGUNA_PUBLIK' or request.session.get("role") == 'ADMIN':
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM SIRUCO.PAKET_MAKAN")
            hasil = cursor_fetchall(cursor)
        context = {'data' : hasil}
    else:
        return redirect('/')
    return render(request, "ListPaketMakan.html", context)


@user_login_required
def update_paket_makan(request):
    if request.session.get("role") != "ADMIN":
        return redirect('/ListPaketMakan')
    
    if request.method == "GET":
        kodehotel = request.GET.get('kodehotel')
        kodepaket = request.GET.get('kodepaket')
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM SIRUCO.PAKET_MAKAN", [kodehotel,kodepaket])
            val = cursor.fetchone()
            print(val)
            key = [col[0] for col in cursor.description]
            print(key)
            data = dict(zip(key, val))
        form = UpdatePaketMakan(initial=data)
    elif request.method == 'POST':
        form = UpdatePaketMakan(request.POST)
        if form.is_valid():
            form.save_update()
            return redirect('/ListPaketMakan')
    context = {'form':form}
    return render(request,'UpdatePaketMakan.html',context) 


@user_login_required
def delete_paket_makan(request):
    if request.method == "GET":
        kodehotel = request.GET.get('kodehotel')
        kodepaket = request.GET.get('kodepaket')
        with connection.cursor() as cursor:
            cursor.execute("DELETE FROM SIRUCO.PAKET_MAKAN WHERE kodehotel=%s and kodepaket=%s", [kodehotel, kodepaket])
    return redirect('/list_paket_makan')


# @user_login_required
# def create_hotel(request):


@user_login_required
def list_hotel(request):
    if request.session.get("role") == 'ADMIN_SATGAS' or request.session.get("role") == 'PENGGUNA_PUBLIK' or request.session.get("role") == 'ADMIN':
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM SIRUCO.HOTEL")
            cursor.execute("SELECT kode, nama, isrujukan, CONCAT(jalan, ', ', kelurahan, ', ', kecamatan, ', ', kabkot, ', ', prov) AS alamat FROM SIRUCO.HOTEL")
            hasil = cursor_fetchall(cursor)
        context = {'data' : hasil}
    else:
        return redirect('/')
    return render(request, "ListHotel.html", context)

@user_login_required
def update_hotel(request):
    if request.session.get("role") == 'ADMIN_SATGAS' or request.session.get("role") == 'PENGGUNA_PUBLIK' or request.session.get("role") == 'ADMIN':
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM SIRUCO.HOTEL")
            hasil = cursor_fetchall(cursor)
        context = {'data' : hasil}
    else:
        return redirect('/')
    return render(request, "UpdateHotel.html", context)

green/templates/CreatePaketMakan.html
{% extends "base.html" %}
{% load static %}

{% block title %}
SIRUCO - Buat Paket Makan
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>Buat Paket Makan</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'green:create_paket_makan' %}" method="post" id="create_paket_makan">
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
            </div>
            {% endif %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-danger alert-dismissable" role="alert">{{ message }}</div>
                {% endfor %}
            </ul>
            {% endif %}

            <h4><label for="{{ form.KodeHotel.id_for_label }}">Kode Hotel</label></h4>
            {% if form.KodeHotel.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodeHotel.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-kode-hotel"></i></span>
                </div>
                {{ form.KodeHotel }}
            </div>

            <h4><label for="{{ form.KodePaket.id_for_label }}">Kode Paket</label></h4>
            {% if form.KodePaket.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodePaket.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-kode-paket"></i></span>
                </div>
                {{ form.KodePaket }}
            </div>
            
            <h4><label for="{{ form.NamaPaket.id_for_label }}">Nama Paket</label></h4>
            {% if form.NamaPaket.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.NamaPaket.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-nama-paket"></i></span>
                </div>
                {{ form.NamaPaket }}
            </div>

            <h4><label for="{{ form.Harga.id_for_label }}">Harga</label></h4>
            {% if form.Harga.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.Harga.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-harga"></i></span>
                </div>
                {{ form.Harga }}
            </div>
            
            <input class="btn btn-outline-success" style="margin-bottom: 1rem;" type="submit" value="Simpan">
        </form>
    </div>
    



{% endblock %}

green/templates/CreateTransaksiMakan.html
{% extends "base.html" %}
{% load static %}

{% block title %}
SIRUCO - Buat Transaksi Makan
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>Buat Transaksi Makan</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>

    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'green:create_transaksi_makan' %}" method="post" id="create_transaksi_makan">
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
            </div>
            {% endif %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-danger alert-dismissable" role="alert">{{ message }}</div>
                {% endfor %}
            </ul>
            {% endif %}
            
            <h4><label for="{{ form.IDTransaksi.id_for_label }}">ID Transaksi</label></h4>
            {% if form.IDTransaksi.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.IDTransaksi.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-id_transaksi"></i></span>
                </div>
                {{ form.IDTransaksi }}
            </div>

            <h4><label for="{{ form.IDTransaksiMakan.id_for_label }}">ID Transaksi Makan</label></h4>
            {% if form.IDTransaksiMakan.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.IDTransaksiMakan.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-id_transaksi_makan"></i></span>
                </div>
                {{ form.IDTransaksiMakan }}
            </div>


            <h4><label for="{{ form.KodeHotel.id_for_label }}">Kode Hotel</label></h4>
            {% if form.KodeHotel.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodeHotel.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-kode-hotel"></i></span>
                </div>
                {{ form.KodeHotel }}
            </div>

            <h4><label for="{{ form.KodePaket.id_for_label }}">Kode Paket</label></h4>
            {% if form.KodePaket.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodePaket.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-kode-paket"></i></span>
                </div>
                {{ form.KodePaket }}
            </div>
            
            <h4><label for="{{ form.KodePaket.id_for_label }}">Kode Paket</label></h4>
            {% if form.KodePaket.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodePaket.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-kode-paket"></i></span>
                </div>
                {{ form.KodePaket }}
            </div>

            <h4><label for="{{ form.KodePaket.id_for_label }}">Kode Paket</label></h4>
            {% if form.KodePaket.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodePaket.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-kode-paket"></i></span>
                </div>
                {{ form.KodePaket }}
            </div>

            <h4><label for="{{ form.KodePaket.id_for_label }}">Kode Paket</label></h4>
            {% if form.KodePaket.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodePaket.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-kode-paket"></i></span>
                </div>
                {{ form.KodePaket }}
            </div>

            <h4><label for="{{ form.KodePaket.id_for_label }}">Kode Paket</label></h4>
            {% if form.KodePaket.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodePaket.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-kode-paket"></i></span>
                </div>
                {{ form.KodePaket }}
            </div>

            <input class="btn btn-outline-success" style="margin-bottom: 1rem;" type="submit" value="Tambah">
            <h4><label for="{{ form.KodePaket.id_for_label }}">Kode Paket</label></h4>
            {% if form.KodePaket.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.KodePaket.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-kode-paket"></i></span>
                </div>
                {{ form.KodePaket }}
            </div>

            <input class="btn btn-outline-success" style="margin-bottom: 1rem;" type="submit" value="Simpan">
        </form>
    </div>
    



{% endblock %}

green/templates/ListHotel.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    List Hotel
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>List Hotel</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>
    
    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-hover" align="center">
            <thead class="thead-dark">
            <tr>
                <th>No.</th>
                <th>Kode</th>
                <th>Hotel</th>
                <th>Rujukan</th>
                <th>Alamat</th>
                <!-- <th>jalan</th>
                <th>kelurahan</th>
                <th>kecamatan</th>
                <th>kabkot</th>
                <th>prov</th> -->

                {% if request.session.role == 'ADMIN' %}
                <th>Action</th>
                {% endif %}

            </tr>
            </thead>
            {% for row in data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.kode }}</td>
                    <td>{{ row.nama }}</td>
                    {% if row.isrujukan == '1' %}
                    <td><i class="fa fa-check-square"></i></td>
                    {% endif %}
                    {% if row.isrujukan == '0' %}
                    <td><i class="fa fa-square-o"></i></td>
                    {% endif %}
                    <td>{{ row.alamat }}</td>
                    <!-- <td>{{ row.jalan }}</td>
                    <td>{{ row.kelurahan }}</td>
                    <td>{{ row.kecamatan }}</td>
                    <td>{{ row.kabkot }}</td>
                    <td>{{ row.prov }}</td> -->

                    {% if request.session.role == 'ADMIN' %}
                    <td>
                        <form action="{% url 'green:update_paket_makan' %}" method="get">
                            <input type="hidden" id="kodehotel" name="kodehotel" value="{{ row.kodehotel }}">
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>
                    </td>
                    {% endif %}
                </tr>              
            {% endfor %}
        </table>
    </div>
    

{% endblock %}

green/templates/ListPaketMakan.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    List Paket Makan
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>List Paket Makan</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>
    
    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-hover" align="center">
            <thead class="thead-dark">
            <tr>
                <th>No.</th>
                <th>Hotel</th>
                <th>Kode Paket</th>
                <th>Nama Paket</th>
                <th>Harga</th>

                {% if request.session.role == 'ADMIN' %}
                <th>Action</th>
                {% endif %}

            </tr>
            </thead>
            {% for row in data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.kodehotel }}</td>
                    <td>{{ row.kodepaket }}</td>
                    <td>{{ row.nama }}</td>
                    <td>{{ row.harga }}</td>

                    {% if request.session.role == 'ADMIN' %}
                    <td>
                        <form action="{% url 'green:update_paket_makan' %}" method="get">
                            <input type="hidden" id="kodehotel" name="kodehotel" value="{{ row.kodehotel }}">
                            <input type="hidden" id="kodepaket" name="kodepaket" value="{{ row.kodepaket }}">
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>

                        <form action="{% url 'green:delete_paket_makan' %}" method="get">
                            <input type="hidden" id="kodehotel" name="kodehotel" value="{{ row.kodehotel }}">
                            <input type="hidden" id="kodepaket" name="kodepaket" value="{{ row.kodepaket }}">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                    </td>
                    {% endif %}
                </tr>              
            {% endfor %}
        </table>
    </div>
    

{% endblock %}

green/templates/ListTransaksiMakan.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    List Transaksi Makan
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>List Transaksi Makan</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>
    
    <div class="container d-flex justify-content-center" align="center">
        <table class="table table-hover" align="center">
            <thead class="thead-dark">
            <tr>
                <th>No.</th>
                <th>Id Transaksi Hotel</th>
                <th>Id Transaksi</th>
                <th>Total Bayar</th>
                {% if request.session.role == 'PENGGUNA_PUBLIK' %}
                <th>Action</th>
                {% endif %}

                {% if request.session.role == 'ADMIN_SATGAS' %}
                <th>Action</th>
                {% endif %}

            </tr>
            </thead>
            {% for row in data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.idtransaksi }}</td>
                    <td>{{ row.idtransaksimakan }}</td>
                    <td>{{ row.totalbayar }}</td>

                    {% if request.session.role == 'PENGGUNA_PUBLIK' %}
                    <td>
                        <form action="{% url 'green:list_transaksi_makan' %}" method="get">
                            <input type="hidden" id="idtransaksimakan" name="idtransaksimakan" value="{{ row.idtransaksimakan }}">
                            <input type="submit" class="btn btn-success" value="Detail">
                        </form>
                                
                    </td>
                    {% endif %}

                    {% if request.session.role == 'ADMIN_SATGAS' %}
                    <td>
                        <form action="{% url 'green:update_transaksi_makan' %}" method="get">
                            <input type="hidden" id="idtransaksimakan" name="idtransaksimakan" value="{{ row.idtransaksimakan }}">
                            <input type="submit" class="btn btn-success" value="Update">
                        </form>

                        <form action="{% url 'green:list_transaksi_makan' %}" method="get">
                            <input type="hidden" id="idtransaksimakan" name="idtransaksimakan" value="{{ row.idtransaksimakan }}">
                            <input type="submit" class="btn btn-success" value="Detail">
                        </form>

                        <form action="{% url 'green:delete_transaksi_makan' %}" method="get">
                            <input type="hidden" id="idtransaksimakan" name="idtransaksimakan" value="{{ row.idtransaksimakan }}">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                    </td>
                    {% endif %}
                </tr>              
            {% endfor %}
        </table>
    </div>
    

{% endblock %}

green/templates/UpdateHotel.html
{% extends "base.html" %}
{% load static %}

{% block title %}
SIRUCO - Update Hotel
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>Update Hotel</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>

{% endblock %}

green/templates/UpdatePaketMakan.html
{% extends "base.html" %}
{% load static %}

{% block title %}
SIRUCO - Update Paket Makan
{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>Update Paket Makan</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>

{% endblock %}