blue/urls.py
from django.urls import path
from . import views

app_name = 'blue'

urlpatterns = [
    path('buat-reservasi-rs/', views.reservasirs, name='reservasirs'),
    path('list-reservasi-rs/', views.listreservasirs, name='listreservasirs'),
    path('ajax/load-semuaruangan/', views.load_semuaruangan, name='ajax_load_semuaruangan'),
    path('ajax/load-semuabed/', views.load_semuabed, name='ajax_load_semuabed'),
    path('delete-reservasi-rs/',views.delete_reservasi_rs, name='delete-reservasi-rs'),
    path('update-reservasi-rs/',views.update_reservasi_rs, name='update-reservasi-rs'),
    path('buat-faskes/',views.faskes, name='buat-faskes'),
    path('list-faskes/', views.listfaskes, name='listfaskes'),
    path('delete-faskes/',views.delete_faskes, name='delete-faskes'),
    path('update-faskes/',views.update_faskes, name='update-faskes'),
    path('detail-faskes/',views.detail_faskes, name='detail-faskes'),
    path('buat-jadwal/',views.jadwal, name='buat-jadwal'),
    path('list-jadwal/', views.listjadwal, name='listjadwal'),
    path('buat-rumah-sakit/',views.rumahsakit, name='buat-rumah-sakit'),
    path('list-rumah-sakit/', views.listrumahsakit, name='listrumahsakit'),
    path('update-rumah-sakit/',views.update_rumahsakit, name='update-rumah-sakit'),
    path('list-transaksi-rs/', views.listtransaksirs, name='listtransaksirs'),
    path('delete-transaksi-rs/',views.delete_transaksi_rs, name='delete-transaksi-rs'),
    path('update-transaksi-rs/',views.update_transaksi_rs, name='update-transaksi-rs'),
]

green/urls.py
from django.urls import path
from . import views

app_name = 'green'

urlpatterns = [
    path('create_transaksi_makan/', views.create_transaksi_makan, name='create_transaksi_makan'),
    path('list_transaksi_makan/', views.list_transaksi_makan, name='list_transaksi_makan'),
    path('update_transaksi_makan/', views.update_transaksi_makan, name='update_transaksi_makan'),
    path('delete_transaksi_makan/', views.delete_transaksi_makan, name='delete_transaksi_makan'),
    path('detail_transaksi_makan/', views.detail_transaksi_makan, name='detail_transaksi_makan'),

    path('create_paket_makan/', views.create_paket_makan, name='create_paket_makan'),
    path('list_paket_makan/', views.list_paket_makan, name='list_paket_makan'),
    path('update_paket_makan/', views.update_paket_makan, name='update_paket_makan'),
    path('delete_paket_makan/', views.delete_paket_makan, name='delete_paket_makan'),

    # path('create_hotel/', views.create_hotel, name='create_hotel'),
    path('list_hotel/', views.list_hotel, name='list_hotel'),
    path('update_hotel/', views.update_hotel, name='update_hotel'),
]

homepage/urls.py
from django.urls import path
from homepage.views import *

urlpatterns = [
    path('profile/', profile, name="profile"),
    path('register/pengguna_publik/', register_pengguna_publik, name="register_pengguna_publik"),
    path('register/admin_satgas/', register_admin_satgas, name="register_admin_satgas"),
    path('register/dokter/', register_dokter, name="register_dokter"),
    path('register/admin/', register_admin, name="register_admin"),
    path('register/', register, name="register"),
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('', home, name="home")
]

jingga/urls.py
from django.urls import path
from jingga.views import *

app_name = 'jingga'
urlpatterns = [
    path('', index, name="index"),
    path('listruanganhotel', listruanganhotel, name="listruanganhotel"),
    path('create-listruanganhotel', createlistruanganhotel, name="create-listruanganhotel"),
    path('ajax/load-kodehotel/', load_kodehotel, name='ajax-load-kodehotel'),
    path('update-ruanganhotel/', updateruanganhotel, name="update-ruanganhotel"),
    path('delete-ruanganhotel/', deleteruanganhotel, name="delete-ruanganhotel"),
    path('listreservasihotel/', listreservasihotel, name="listreservasihotel"),
    path('create-reservasihotel/', createreservasihotel, name="create-reservasihotel"),
    path('ajax/load-semuakodehotel/', load_semuakodehotel, name='ajax-load-semuakodehotel'),
    path('update-reservasihotel/', updatereservasihotel, name="update-reservasihotel"),
    path('delete-reservasihotel/', deletereservasihotel, name="delete-reservasihotel"),
    path('listtransaksihotel', listtransaksihotel, name="listtransaksihotel"),
    path('update-transaksihotel/', updatetransaksihotel, name="update-transaksihotel"),
    path('listtransaksibooking', listtransaksibooking, name="listtransaksibooking"),
]

pasien/urls.py
from django.urls import path, include
from .views import *

app_name = 'pasien'

urlpatterns = [
    path('list_pasien/', list_pasien, name="list_pasien"),
    path('create_pasien/', create_pasien, name="create_pasien"),
    path('detail_pasien/', detail_pasien, name="detail_pasien"),
    path('update_pasien/', update_pasien, name="update_pasien"),
    path('delete_pasien/', delete_pasien, name="delete_pasien"),
]

purple/urls.py
from django.urls import path, include
from .views import *

app_name = 'purple'
urlpatterns = [ 
	path('create_jadwal_dokter/', create_jadwal_dokter, name='create_jadwal_dokter'), 
	path('list_jadwal_dokter/', list_jadwal_dokter, name='list_jadwal_dokter'),
	path('list_jadwal/', list_jadwal, name='list_jadwal'),

	path('create_appointment/', create_appointment, name='create_appointment'), 
	path('list_appointment/', list_appointment, name='list_appointment'),
	path('form_appointment/', form_appointment, name='form_appointment'),
	path('delete_appointment/', delete_appointment, name='delete_appointment'),
	path('update_appointment/', update_appointment, name='update_appointment'),
	path('ajaxAppointment/', ajaxAppointment, name='ajaxAppointment'),

	path('create_ruangan_rs/', create_ruangan_rs, name='create_ruangan_rs'),
	path('list_ruangan_rs/', list_ruangan_rs, name='list_ruangan_rs'),
	path('update_ruangan_rs/', update_ruangan_rs, name='update_ruangan_rs'),
	path('ajaxRuanganRS/', ajaxRuanganRS, name='ajaxRuanganRS'),
	path('ajaxRuanganRS2/', ajaxRuanganRS2, name='ajaxRuanganRS2'),

	path('create_bed_rs/', create_bed_rs, name='create_bed_rs'), 
	path('list_bed_rs/', list_bed_rs, name='list_bed_rs'), 
	path('ajaxBedRS/', ajaxBedRS, name='ajaxBedRS'),
	path('ajaxBedRS2/', ajaxBedRS2, name='ajaxBedRS2'),
	path('delete_bed_rs/', delete_bed_rs, name='delete_bed_rs'),
]

tk4_b4/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('green.urls')),
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('jingga.urls')),
    path('', include('purple.urls')),
    path('', include('pasien.urls')),
    path('', include('blue.urls')),
    
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.db import connection
from django.shortcuts import render, redirect
from homepage.forms import *
from django.contrib import messages

def home(request):
    return render(request, "index.html")

def no_user(function):
    def wrapper(request, *args, **kwargs):
        username = request.session.get('username')
        nama = request.session.get('nama')
        if username is not None:
            return redirect('/profile/')
        else:
            return function(request, *args, **kwargs)
    return wrapper


def check_role(username):
    with connection.cursor() as cursor:
        for i in ["PENGGUNA_PUBLIK", "ADMIN_SATGAS", "DOKTER", "ADMIN"]:
            cursor.execute(
                f"SELECT * FROM siruco.{i} WHERE username=%s LIMIT 1;",
                [username])
            if cursor.fetchone() is not None:
                return i

def user_login_required(function):
    def wrapper(request, *args, **kwargs):
        username = request.session.get('username')
        if username is None:
            return redirect('/login/')
        else:
            return function(request, *args, **kwargs)
    return wrapper


def get_role_data(username, role):
    print(role)
    with connection.cursor() as cursor:
        cursor.execute(
            f"SELECT * FROM siruco.{role} WHERE username=%s LIMIT 1;",
            [username])
        return cursor.fetchone()

def input_session(request, username, nama):
    request.session['username'] = username
    request.session['nama'] = nama
    request.session['role'] = check_role(username)

@no_user
def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        try:
            if form.is_valid():
                    with connection.cursor() as cursor:
                        cursor.execute(
                            "SELECT * FROM siruco.AKUN_PENGGUNA WHERE username=%s;",
                            [form.cleaned_data.get('username')])
                        data = cursor.fetchone()
                    input_session(request, form.cleaned_data.get('username'), data[0])
                    return redirect('/profile/')
        except:
            messages.warning(request, 'Username salah')
    elif request.method == 'GET':
        form = LoginForm()
    context = {'form': form}
    return render(request, "login.html", context)


def logout(request):
    request.session.flush()
    return redirect('/')


@no_user
def register(request):
    if request.method == 'POST':
        form = RolePickerForm(request.POST)
        if form.is_valid():
            url_map = {'PENGGUNA_PUBLIK': '/register/pengguna_publik/',
                       'ADMIN_SATGAS': '/register/admin_satgas/',
                       'DOKTER': '/register/dokter/',
                       'ADMIN': '/register/admin/'}
            return redirect(url_map[form.cleaned_data.get('peran')])
    elif request.method == 'GET':
        form = RolePickerForm()
    context = {'form': form}
    return render(request, "register.html", context)

@no_user
def register_pengguna_publik(request):
    if request.method == 'POST':
        form1 = RegisterPenggunaPublik(request.POST)
        if form1.is_valid():
            try:
                form1.save()
                nama = form1.cleaned_data.get('nama')
                input_session(request, form1.cleaned_data.get('username'), nama)
                return redirect('/profile/')
            except:
                return render(request, 'register_pengguna_publik.html', {'form1': form1, 'message': 'Password harus terdiri dari minimal 1 huruf kapital dan 1 angka.'})
    elif request.method == 'GET':
        form1 = RegisterPenggunaPublik()
    context = {'form1': form1}
    return render(request, "register_pengguna_publik.html", context)

@no_user
def register_admin_satgas(request):
    if request.method == 'POST':
        form2 = RegisterAdminSatgasForm(request.POST)
        if form2.is_valid():
            try:
                form2.save()
                nama = 'Admin'
                input_session(request, form2.cleaned_data.get('username'), nama)
                return redirect('/profile/')
            except:
                return render(request, 'register_admin_satgas.html', {'form2': form2, 'message': 'Password harus terdiri dari minimal 1 huruf kapital dan 1 angka.'})
    elif request.method == 'GET':
        form2 = RegisterAdminSatgasForm()
    context = {'form': form2}
    return render(request, "register_admin_satgas.html", context)


@no_user
def register_dokter(request):
    if request.method == 'POST':
        form = RegisterDokterForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                nama = form.cleaned_data.get('nama')
                input_session(request, form.cleaned_data.get('username'), nama)
                return redirect('/profile/')
            except:
                return render(request, 'register_dokter.html', {'form': form, 'message': 'Password harus terdiri dari minimal 1 huruf kapital dan 1 angka.'})
    elif request.method == 'GET':
        form = RegisterDokterForm()
    context = {'form': form}
    return render(request, "register_dokter.html", context)


@no_user
def register_admin(request):
    if request.method == 'POST':
        form = RegisterAdminForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                nama = 'Admin'
                input_session(request, form.cleaned_data.get('username'), nama)
                return redirect('/profile/')
            except:
                return render(request, 'register_admin.html', {'form': form, 'message': 'Password harus terdiri dari minimal 1 huruf kapital dan 1 angka.'})
    elif request.method == 'GET':
        form = RegisterAdminForm()
    context = {'form': form}
    return render(request, "register_admin.html", context)

@user_login_required
def profile(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM siruco.AKUN_PENGGUNA WHERE username=%s",
                       [request.session.get("username")])
        user_data = cursor.fetchone()
        role_data = get_role_data(
            request.session.get("username"),
            request.session.get("role"))
    context = {'user': user_data, 'role': role_data}
    return render(request, "profile.html", context)

homepage/templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="d-flex flex-column justify-content-center align-items-center" id="spinner" style="display:inline; height:100vh">
            <div class="d-flex justify-content-center align-items-center mb-4" style="width:100%">
                <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
            <div class="justify-content-center" align="middle">
                <h3>SIRUCO</h3>
                <hr>
                <p>"Your best solution for COVID-19 attacks"</p>
            </div>
        </div>
        <div id="core" style="display:none">
            {% include 'navbar.html' %}
            {% block content %}

            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="  crossorigin="anonymous"></script>
        {% block addscript %}
        {% endblock addscript %}
        <script src="{% static 'js/main.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

homepage/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home - SIRUCO{% endblock %}

{% block content %}
<div class='jumbotron justify-content-center' align="center">
    <h4>Selamat Datang di</h4>
    <hr>
    <h1>SIRUCO</h1>
</div>
{% endblock %}

homepage/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}Login - SIRUCO{% endblock %}

{% block content %}
    <div class='jumbotron justify-content-center' align="center">
        <h1>Login</h1>
        <hr>
        <h4>SIRUCO</h4>
    </div>
    <div class="container d-flex justify-content-center" align="center">
        <form action="{% url 'login' %}" method="post">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-danger alert-dismissable" role="alert">{{ message }}</div>
                {% endfor %}
            </ul>
            {% endif %}
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
            </div>
            {% endif %}
            <h4><label for="{{ form.username.id_for_label }}">Email</label></h4>
            {% if form.username.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.username.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                </div>
                {{ form.username }}
            </div>

            <h4><label for="{{ form.password.id_for_label }}">Password</label></h4>
            {% if form.password.errors %}
            <div class="alert alert-danger" role="alert">
            {{ form.password.errors }}
            </div>
            {% endif %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-key"></i></span>
                </div>
                {{ form.password }}
            </div>

            <input class="btn btn-outline-primary" type="submit" value="Login">
        </form>
    </div>
    <div class="container">
    <hr>
    </div>
    <div class="container justify-content-center" align="center">
        <h4>Belum punya akun?</h4>
        <a href="{% url 'register' %}" class="btn btn-outline-primary">Daftar sekarang!</a>
    </div>
{% endblock %}

homepage/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid d-flex mr-auto">
        <a class="navbar-brand" href="{% url 'home' %}" style="font-family: 'Abril Fatface'; color:rgb(35, 63, 40);">
            <i class="d-inline-block align-center fa fa-medkit" style="color:green;"></i>
            SIRUCO
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

    <ul class="nav navbar-nav justify-content-start">
        {% if request.session.username %}
        {% if request.session.role != 'ADMIN' %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Pasien
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% if request.session.role == 'PENGGUNA_PUBLIK' %}
        <a class="dropdown-item" href="{% url 'pasien:create_pasien' %}">Pendaftaran Pasien</a>
        <a class="dropdown-item" href="{% url 'pasien:list_pasien' %}">List Pasien</a>
        {% endif %}
        
        {% if request.session.role == 'PENGGUNA_PUBLIK' or request.session.role == 'ADMIN_SATGAS' %}
        <a class="dropdown-item" href="{% url 'purple:create_appointment' %}">Buat Appointment</a>
        {% endif %}

        {% if request.session.role == 'PENGGUNA_PUBLIK' or request.session.role == 'ADMIN_SATGAS' or request.session.role == 'DOKTER' %}
        <a class="dropdown-item" href="{% url 'purple:list_appointment' %}">List Appointment</a>
        <a class="dropdown-item" href="#">List Hasil Tes Pasien</a>
        {% endif %}

        {% if request.session.role == 'DOKTER' %}
        <a class="dropdown-item" href="#">Buat Hasil Tes Pasien</a>
        {% endif %}
        </div>
        </li>
        {% endif %}


        {% if request.session.role != 'ADMIN' %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Rumah Sakit
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% if request.session.role == 'ADMIN_SATGAS' %}
        <a class="dropdown-item" href="{%url 'blue:buat-rumah-sakit' %}">Buat RS</a>
        <a class="dropdown-item" href="{%url 'blue:listrumahsakit' %}">List RS</a>
        <a class="dropdown-item" href="{% url 'purple:create_ruangan_rs' %}">Buat Ruangan RS</a>
        <a class="dropdown-item" href="{% url 'purple:list_ruangan_rs' %}">List Ruangan RS</a>
        <a class="dropdown-item" href="{% url 'purple:create_bed_rs' %}">Buat Bed RS</a>
        <a class="dropdown-item" href="{% url 'purple:list_bed_rs' %}">List Bed RS</a>        
        <a class="dropdown-item" href="{%url 'blue:reservasirs' %}">Buat Reservasi RS</a>
        {% endif %}
        
        {% if request.session.role == 'PENGGUNA_PUBLIK' or request.session.role == 'ADMIN_SATGAS' %}
        <a class="dropdown-item" href="{%url 'blue:listreservasirs' %}">List Reservasi RS</a>
        {% endif %}

        {% if request.session.role == 'PENGGUNA_PUBLIK' or request.session.role == 'ADMIN_SATGAS' or request.session.role == 'DOKTER' %}
        <a class="dropdown-item" href="{% url 'purple:list_jadwal_dokter' %}">List Jadwal Dokter</a>
        {% endif %}

        {% if request.session.role == 'DOKTER' %}
        <a class="dropdown-item" href="{% url 'purple:list_jadwal' %}">Buat Jadwal Dokter</a>
        {% endif %}
        </div>
        </li>
        {% endif %}

        {% if request.session.role != 'DOKTER' %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Hotel
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% if request.session.role == 'ADMIN' %}
        <a class="dropdown-item" href="{%url 'green:list_hotel' %}">Buat Hotel</a>
        <a class="dropdown-item" href="{%url 'green:list_hotel' %}">List Hotel</a>
        <a class="dropdown-item" href="{% url 'jingga:create-listruanganhotel' %}">Buat Ruangan Hotel</a>
        <a class="dropdown-item" href="{% url 'jingga:listruanganhotel' %}">List Ruangan Hotel</a>
        <a class="dropdown-item" href="{%url 'green:create_paket_makan' %}">Buat Paket Makan</a>
        <a class="dropdown-item" href="{%url 'green:list_paket_makan' %}">List Paket Makan</a>        
        {% endif %}
        
        {% if request.session.role == 'PENGGUNA_PUBLIK' %}
        <a class="dropdown-item" href="{%url 'green:list_hotel' %}">List Hotel</a>
        <a class="dropdown-item" href="{% url 'jingga:listruanganhotel' %}">List Ruangan Hotel</a>
        <a class="dropdown-item" href="{%url 'green:list_paket_makan' %}">List Paket Makan</a>
        <a class="dropdown-item" href="{% url 'jingga:create-reservasihotel' %}">Buat Reservasi Hotel</a>
        <a class="dropdown-item" href="{% url 'jingga:listreservasihotel' %}">List Reservasi Hotel</a>
        {% endif %}

        {% if request.session.role == 'ADMIN_SATGAS' %}
        <a class="dropdown-item" href="{%url 'green:list_hotel' %}">List Hotel</a>
        <a class="dropdown-item" href="{% url 'jingga:listruanganhotel' %}">List Ruangan Hotel</a>
        <a class="dropdown-item" href="{%url 'green:list_paket_makan' %}">List Paket Makan</a>
        <a class="dropdown-item" href="{% url 'jingga:create-reservasihotel' %}">Buat Reservasi Hotel</a>
        <a class="dropdown-item" href="{% url 'jingga:listreservasihotel' %}">List Reservasi Hotel</a>
        {% endif %}
        </div>
        </li>
        {% endif %}

        {% if request.session.role == 'ADMIN_SATGAS' or request.session.role == 'PENGGUNA_PUBLIK' %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Transaksi
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% if request.session.role == 'ADMIN_SATGAS' %}
        <a class="dropdown-item" href="#">List Transaksi RS</a>
        <a class="dropdown-item" href="{% url 'jingga:listtransaksihotel' %}">List Transaksi Hotel</a>
        <a class="dropdown-item" href="{% url 'jingga:listtransaksibooking' %}">List Transaksi Booking Hotel</a>
        <a class="dropdown-item" href="{%url 'blue:listtransaksirs' %}">List Transaksi RS</a>
        <a class="dropdown-item" href="{%url 'green:create_transaksi_makan' %}">Buat Transaksi Makan dan Daftar Pesan</a>
        <a class="dropdown-item" href="{%url 'green:list_transaksi_makan' %}">List Transaksi Makan dan Daftar Pesan</a>
        {% endif %}
        
        {% if request.session.role == 'PENGGUNA_PUBLIK' %}
        <a class="dropdown-item" href="#">Bayar Transaksi RS</a>
        <a class="dropdown-item" href="#">Bayar Transaksi Hotel</a>
        <a class="dropdown-item" href="{% url 'jingga:listtransaksibooking' %}">List Transaksi Booking Hotel</a>
        <a class="dropdown-item" href="{%url 'green:create_transaksi_makan' %}">Buat Transaksi Makan dan Daftar Pesan</a>
        <a class="dropdown-item" href="{%url 'green:list_transaksi_makan' %}" role="button">List Transaksi Makan dan Daftar Pesan</a>
        {% endif %}
        </div>
        </li>
        {% endif %}

        {% if request.session.role == 'ADMIN_SATGAS' %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Faskes
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item" href="{%url 'blue:buat-faskes' %}">Buat Faskes</a>
        <a class="dropdown-item" href="{%url 'blue:listfaskes' %}">List Faskes</a>
        <a class="dropdown-item" href="{%url 'blue:buat-jadwal' %}">Buat Jadwal Faskes</a>
        <a class="dropdown-item" href="{%url 'blue:listjadwal' %}">List Jadwal Faskes</a>
        {% endif %}
        </div>
        </li>
        {% endif %}
    </ul>

        <ul class="d-flex align-items-center nav navbar-nav ml-auto justify-content-end">
        {% if request.session.username %}
        <li class="navbar-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" align="right" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span>
        <strong>{{ request.session.nama }}</strong> <i class="fa fa-user"></i>
        </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
        </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        {% endif %}
        </ul>
        </div>
    </div>
</nav>